import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, CalendarClock, CircleAlert, Clock3, MapPinned, PhoneCall, ReceiptText, Users, Wrench } from "lucide-react";
import type { SalesAgendaItem, SalesDashboardData } from "@/lib/dashboard/sales-dashboard";

export function SalesCommandCenter({ data }: { data: SalesDashboardData }) {
  return <main className="focus-shell py-7"><div className="focus-container grid min-w-0 gap-7">
    <header className="flex flex-wrap items-end justify-between gap-5 border-b border-focus-line pb-6"><div><p className="text-xs font-black uppercase text-focus-yellow">Centru de lucru comercial</p><h1 className="mt-1 font-display text-3xl font-black uppercase text-white sm:text-4xl">Agenda mea</h1><p className="mt-2 max-w-3xl text-sm text-slate-300">Bună, {data.userName.split(" ")[0]}. Aici sunt acțiunile tale, ordonate după urgență.</p></div><div className="flex flex-wrap gap-2"><Link className="focus-button" href="/admin/selectie-locatii" prefetch={false}><MapPinned size={18} /> Selector ofertă</Link><Link className="focus-button secondary" href="/admin/crm?view=today" prefetch={false}><PhoneCall size={18} /> CRM astăzi</Link></div></header>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5" aria-label="Rezumat agenda mea">
      <SalesMetric icon={<PhoneCall size={18} />} label="De urmărit azi" value={data.summary.followUpsDue} detail={`${data.summary.overdueFollowUps} restante`} tone={data.summary.overdueFollowUps ? "red" : "green"} href="/admin/crm?view=today" />
      <SalesMetric icon={<ReceiptText size={18} />} label="Scadențe clienții mei" value={data.summary.overdueInvoices} detail={`${data.summary.dueSoonInvoices} în următoarele 7 zile`} tone={data.summary.overdueInvoices ? "red" : "green"} href="/admin/clienti?tab=invoices" />
      <SalesMetric icon={<BriefcaseBusiness size={18} />} label="Încep curând" value={data.summary.campaignsStarting} detail="Campanii în 7 zile" tone="yellow" href="/admin/campanii" />
      <SalesMetric icon={<CalendarClock size={18} />} label="Se termină curând" value={data.summary.campaignsEnding} detail="Campanii în 7 zile" tone="neutral" href="/admin/campanii" />
      <SalesMetric icon={<Wrench size={18} />} label="Probleme operaționale" value={data.summary.operationalProblems} detail="La clienții mei" tone={data.summary.operationalProblems ? "red" : "green"} href="/admin/operational" />
    </section>

    <section className="border-y border-focus-line py-6"><SectionHeader eyebrow="Prioritate zilnică" title="Ce am de făcut azi" description="Facturi, follow-up-uri, campanii și execuție, într-o singură listă." /><div className="mt-5 grid gap-2">{data.agenda.length ? data.agenda.map((item) => <AgendaRow item={item} key={item.id} />) : <Empty text="Nu ai acțiuni urgente. Verifică CRM-ul pentru următoarea oportunitate." />}</div></section>

    <div className="grid gap-7 xl:grid-cols-2">
      <section><SectionHeader eyebrow="Încasări" title="Scadențe clienții mei" description="Sunt afișate numai facturile asociate portofoliului tău." action={<Link className="section-link" href="/admin/clienti?tab=invoices" prefetch={false}>Vezi facturile <ArrowRight size={14} /></Link>} /><div className="mt-4 overflow-x-auto rounded-lg border border-focus-line"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-focus-navy/80 text-xs uppercase text-slate-400"><tr><th className="px-4 py-3">Client / factură</th><th className="px-4 py-3">Scadență</th><th className="px-4 py-3 text-right">Sold</th><th className="px-4 py-3 text-right">Acțiune</th></tr></thead><tbody>{data.invoices.map((row) => <tr className="border-t border-focus-line" key={row.id}><td className="px-4 py-3"><strong className="block text-white">{row.clientName}</strong><small className="text-slate-400">{row.invoiceNumber}</small></td><td className={`px-4 py-3 font-bold ${row.daysUntilDue != null && row.daysUntilDue < 0 ? "text-red-200" : "text-slate-200"}`}>{row.dueDate ? formatDate(row.dueDate) : "Fără termen"}<small className="block text-slate-400">{dayLabel(row.daysUntilDue)}</small></td><td className="px-4 py-3 text-right font-black text-white">{formatMoney(row.amount)} {row.currency}</td><td className="px-4 py-3 text-right"><Link className="section-link justify-end" href={row.href} prefetch={false}>Vezi clientul <ArrowRight size={14} /></Link></td></tr>)}</tbody></table>{!data.invoices.length ? <Empty text="Nu ai facturi scadente sau apropiate de termen." /> : null}</div></section>

      <section><SectionHeader eyebrow="CRM" title="Follow-up-uri" description="Restantele și acțiunile apropiate de termen." action={<Link className="section-link" href="/admin/crm?view=today" prefetch={false}>Deschide agenda CRM <ArrowRight size={14} /></Link>} /><div className="mt-4 grid gap-2">{data.followUps.length ? data.followUps.map((row) => <Link className={`flex items-center justify-between gap-3 rounded-lg border px-4 py-3 text-sm transition hover:border-focus-yellow ${row.overdue ? "border-red-300/30 bg-red-500/10" : "border-focus-line bg-focus-ink/55"}`} href={row.href} key={row.id} prefetch={false}><span className="min-w-0"><strong className="block truncate text-white">{row.companyName}</strong><small className="block truncate text-slate-400">{row.description}</small></span><time className={row.overdue ? "font-black text-red-200" : "font-bold text-focus-yellow"}>{formatDate(row.dueDate)}</time></Link>) : <Empty text="Nu ai follow-up-uri planificate în următoarele 7 zile." />}</div></section>
    </div>

    <div className="grid gap-7 border-t border-focus-line pt-7 xl:grid-cols-[1.1fr_0.9fr]">
      <section><SectionHeader eyebrow="Portofoliul meu" title="Campaniile mele" description="Active, cu start sau final apropiat." action={<Link className="section-link" href="/admin/campanii" prefetch={false}>Vezi toate <ArrowRight size={14} /></Link>} /><div className="mt-4 grid gap-2">{data.campaigns.length ? data.campaigns.map((row) => <Link className="grid gap-2 rounded-lg border border-focus-line bg-focus-ink/55 px-4 py-3 text-sm transition hover:border-focus-yellow sm:grid-cols-[1fr_auto]" href={row.href} key={row.id} prefetch={false}><span className="min-w-0"><strong className="block truncate text-white">{row.clientName}</strong><small className="block truncate text-slate-400">{row.campaignName}</small></span><span className="text-xs font-bold text-slate-300">{row.startDate ? formatDate(row.startDate) : "-"} → {row.endDate ? formatDate(row.endDate) : "-"}</span></Link>) : <Empty text="Nu ai campanii active în intervalul apropiat." />}</div></section>
      <section><SectionHeader eyebrow="Execuție" title="Operațional la clienții mei" description="Decorări și neutralizări care îți pot afecta campaniile." action={<Link className="section-link" href="/admin/operational" prefetch={false}>Vezi operațional <ArrowRight size={14} /></Link>} /><div className="mt-4 grid gap-2">{data.operations.length ? data.operations.map((row) => <Link className={`flex items-center justify-between gap-3 rounded-lg border px-4 py-3 text-sm transition hover:border-focus-yellow ${row.overdue ? "border-red-300/30 bg-red-500/10" : "border-focus-line bg-focus-ink/55"}`} href={row.href} key={row.id} prefetch={false}><span className="min-w-0"><strong className="block truncate text-white">{row.locationCode} · {row.clientName}</strong><small className="block truncate text-slate-400">{row.kind === "decoration" ? "Decorare" : "Neutralizare"} · {row.campaignName || "Fără campanie"}</small></span><time className={row.overdue ? "font-black text-red-200" : "font-bold text-focus-yellow"}>{row.dueDate ? formatDate(row.dueDate) : "-"}</time></Link>) : <Empty text="Nu ai probleme operaționale active." />}</div></section>
    </div>

    <section className="border-t border-focus-line pt-7"><SectionHeader eyebrow="Scurtături" title="Acțiuni rapide" description="Mergi direct în fluxul în care lucrezi." /><div className="mt-4 flex flex-wrap gap-2"><Link className="focus-button" href="/admin/selectie-locatii" prefetch={false}><MapPinned size={17} /> Deschide Selector ofertă</Link><Link className="focus-button secondary" href="/admin/crm?view=today" prefetch={false}><PhoneCall size={17} /> Adaugă follow-up</Link><Link className="focus-button secondary" href="/admin/clienti" prefetch={false}><Users size={17} /> Vezi clienții mei</Link><Link className="focus-button secondary" href="/admin/clienti?tab=invoices" prefetch={false}><ReceiptText size={17} /> Facturile clienților mei</Link><Link className="focus-button secondary" href="/admin/campanii" prefetch={false}><BriefcaseBusiness size={17} /> Campaniile mele</Link></div></section>
    <p className="text-right text-xs text-slate-500">Actualizat {formatDateTime(data.generatedAt)}</p>
  </div></main>;
}

function SalesMetric({ icon, label, value, detail, tone, href }: { icon: React.ReactNode; label: string; value: number; detail: string; tone: "neutral" | "green" | "yellow" | "red"; href: string }) { const color = { neutral: "text-white", green: "text-emerald-200", yellow: "text-focus-yellow", red: "text-red-200" }[tone]; return <Link className="min-h-32 rounded-lg border border-focus-line bg-focus-ink/65 p-4 transition hover:border-focus-yellow" href={href} prefetch={false}><div className="flex items-center justify-between text-slate-400"><span className="text-xs font-black uppercase">{label}</span>{icon}</div><strong className={`mt-3 block text-3xl font-black ${color}`}>{value}</strong><span className="mt-1 block text-xs text-slate-400">{detail}</span></Link>; }
function AgendaRow({ item }: { item: SalesAgendaItem }) { const icon = item.kind === "invoice" ? <ReceiptText size={17} /> : item.kind === "follow_up" ? <PhoneCall size={17} /> : item.kind === "operation" ? <Wrench size={17} /> : item.kind === "campaign_end" ? <Clock3 size={17} /> : <BriefcaseBusiness size={17} />; const tone = item.urgency === "critical" ? "border-red-300/35 bg-red-500/10" : item.urgency === "high" ? "border-amber-300/35 bg-amber-400/10" : "border-focus-line bg-focus-ink/55"; return <article className={`grid gap-3 rounded-lg border px-4 py-3 md:grid-cols-[minmax(0,1fr)_auto] ${tone}`}><div className="min-w-0"><div className="flex items-center gap-2 text-focus-yellow">{icon}<strong className="truncate text-sm text-white">{item.title}</strong></div><p className="mt-1 text-sm text-slate-300">{item.context}</p></div><div className="flex flex-wrap items-center gap-4 md:justify-end">{item.amount ? <strong className="text-sm text-white">{formatMoney(item.amount)} {item.currency}</strong> : null}{item.dueDate ? <time className="text-xs font-bold text-slate-300">{formatDate(item.dueDate)}</time> : null}<Link className="section-link" href={item.href} prefetch={false}>{item.actionLabel}<ArrowRight size={14} /></Link></div></article>; }
function SectionHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase text-focus-yellow">{eyebrow}</p><h2 className="mt-1 text-2xl font-black text-white">{title}</h2><p className="mt-1 max-w-2xl text-sm text-slate-400">{description}</p></div>{action}</div>; }
function Empty({ text }: { text: string }) { return <div className="flex items-center gap-2 rounded-lg border border-dashed border-focus-line p-5 text-sm text-slate-400"><CircleAlert size={18} />{text}</div>; }
function dayLabel(days: number | null) { if (days == null) return "Termen necunoscut"; if (days < 0) return `${Math.abs(days)} zile întârziere`; if (days === 0) return "Scadentă azi"; return `În ${days} zile`; }
function formatMoney(value: string) { return new Intl.NumberFormat("ro-RO", { maximumFractionDigits: 2 }).format(Number(value || 0)); }
function formatDate(value: string) { return new Intl.DateTimeFormat("ro-RO", { day: "2-digit", month: "2-digit", year: "numeric", timeZone: "UTC" }).format(new Date(value)); }
function formatDateTime(value: string) { return new Intl.DateTimeFormat("ro-RO", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit", timeZone: "Europe/Bucharest" }).format(new Date(value)); }
